#!/bin/sh

# Generate config
cat /etc/tmp | jq --arg a "$PORT" --arg b "$KEY" --arg c "$SPATH" --arg d "$REDIRECT" '.inbounds[0].port=$a | .inbounds[0].settings.clients[0].id=$b | .inbounds[0].streamSettings.wsSettings.path=$c | .inbounds[0].streamSettings.wsSettings.redirect=$d' > /home/xray/.config.json

# Start the server
SHELL=/bin/ash ttyd -i lo -p $USER tmux new -A -s slice &> /dev/null & \
xray -c /home/xray/.config.json & \
wait
