#!/bin/sh

cat << EOF > /etc/project.json
{
    "inbounds": [
        {
            "type": "vmess",
            "listen": "::",
            "listen_port": $PORT,
            "users": [
                {
                    "name": "nomansnet",
                    "uuid": "$KEY",
                    "alterId": 0
                }
            ],
            "transport": {
                "type": "http",
                "path": "$SPATH",
                "redirect": "$REDIRECT"
            }
        }
    ]
}
EOF

# Start the server
cd $HOME && SHELL=/bin/ash ttyd -i lo -p $USER tmux new -A -s project &> /dev/null & \
project -c /etc/project.json run &> /dev/null & \
wait
